"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import type { BulkStudentDeleteState } from "@/actions/person-roster";
import type { PersonFilter, PersonSummary } from "@/lib/person-roster";

const labels: Partial<Record<PersonFilter, string>> = { ATTENDED_UNREGISTERED: "上過課未註冊", PENDING_REGISTRATION: "待開通", POSSIBLE_MISSING_ACCESS: "可能缺權限", HAS_ACCESS: "有影片", LEGACY: "舊站", LEAD: "潛在", IDENTITY_CONFLICT: "身分待確認", SAFE_TO_DELETE: "可安全刪除", SUSPECTED_TEST: "疑似測試", ARCHIVED: "已封存" };
const hrefFor = (p: PersonSummary) => `/admin/people/${p.kind}/${encodeURIComponent(p.kind === "student" ? p.studentId! : p.kind === "member" ? p.userId! : p.email!)}`;

export function PeopleTable({ rows, canBulkDelete, action }: {
  rows: PersonSummary[]; canBulkDelete: boolean;
  action: (prev: BulkStudentDeleteState, fd: FormData) => Promise<BulkStudentDeleteState>;
}) {
  const [selected, setSelected] = useState<string[]>([]); const [preview, setPreview] = useState(false);
  const [state, formAction, pending] = useActionState(action, null);
  const selectable = rows.filter((r) => r.studentId).slice(0, 50);
  const selectedRows = rows.filter((r) => r.studentId && selected.includes(r.studentId));
  const groups = { eligible: selectedRows.filter((r) => r.deleteStatus === "ELIGIBLE"), protected: selectedRows.filter((r) => r.deleteStatus === "PROTECTED"), review: selectedRows.filter((r) => r.deleteStatus === "REVIEW") };
  const toggle = (id: string) => { setPreview(false); setSelected((cur) => cur.includes(id) ? cur.filter((v) => v !== id) : cur.length < 50 ? [...cur, id] : cur); };
  const allSelected = selectable.length > 0 && selectable.every((r) => selected.includes(r.studentId!));
  return <section className="overflow-hidden rounded-xl border border-gray-200 bg-white">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b px-4 py-3 text-sm text-gray-500"><span>目前顯示 {rows.length} 人</span>{canBulkDelete && <div className="flex items-center gap-3"><span>已選 {selected.length}/50</span><button type="button" disabled={!selected.length} onClick={() => setPreview(true)} className="rounded-lg border border-red-300 px-3 py-1.5 font-medium text-red-700 disabled:opacity-40">預覽批次刪除</button></div>}</div>
    {rows.some((r) => r.testCandidateReasons.length > 0) && <div className="border-b border-orange-100 bg-orange-50 px-4 py-3 text-xs text-orange-800">疑似測試只是一組候選提示，不會自動刪除。理由可在候選清單中查看：{rows.filter((r) => r.testCandidateReasons.length > 0).slice(0, 10).map((r) => `${r.name}（${r.testCandidateReasons.join("、")}）`).join("；")}{rows.filter((r) => r.testCandidateReasons.length > 0).length > 10 ? "……" : ""}</div>}
    {preview && <div className="border-b border-red-200 bg-red-50 p-4"><h3 className="font-semibold text-red-900">刪除預覽</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-white p-3"><b className="text-green-700">可刪除 {groups.eligible.length}</b><p className="mt-1 text-xs text-gray-500">沒有影片權限，會刪除名單卡及其歷史／接觸紀錄。</p></div><div className="rounded-lg bg-white p-3"><b className="text-red-700">禁止刪除 {groups.protected.length}</b><p className="mt-1 text-xs text-gray-500">已有影片權限，執行時自動略過。</p></div><div className="rounded-lg bg-white p-3"><b className="text-purple-700">人工確認 {groups.review.length}</b><p className="mt-1 text-xs text-gray-500">身分或共用 Email 有疑義，不進入批次刪除。</p></div></div>
      <form action={formAction} className="mt-4 space-y-3">{selected.map((id) => <input key={id} type="hidden" name="studentIds" value={id}/>)}<label className="block text-sm font-medium">整批刪除原因<input name="reason" required minLength={2} placeholder="例如：清除舊官網測試名單" className="mt-1 block w-full max-w-xl rounded-lg border border-red-300 bg-white px-3 py-2"/></label><label className="block text-sm font-medium">輸入「DELETE {selected.length}」確認<input name="confirmation" required autoComplete="off" className="mt-1 block w-full max-w-xl rounded-lg border border-red-300 bg-white px-3 py-2"/></label><div className="flex gap-2"><button disabled={pending || groups.eligible.length === 0} className="rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{pending ? "執行中…" : `確認刪除可刪除的 ${groups.eligible.length} 筆`}</button><button type="button" onClick={() => setPreview(false)} className="px-3 py-2 text-sm text-gray-600">取消</button></div></form>
      {state?.error && <p className="mt-3 text-sm text-red-700">{state.error}</p>}{state && !state.error && <div className="mt-4 rounded-lg border bg-white p-3 text-sm"><b>執行結果</b><p className="mt-1">成功 {state.deleted?.length ?? 0}、權限保護略過 {state.protected?.length ?? 0}、待人工確認 {state.review?.length ?? 0}、失敗 {state.failed?.length ?? 0}</p>{[...(state.protected ?? []), ...(state.review ?? []), ...(state.failed ?? [])].length > 0 && <ul className="mt-2 list-disc pl-5 text-gray-600">{[...(state.protected ?? []), ...(state.review ?? []), ...(state.failed ?? [])].map((r) => <li key={`${r.id}-${r.reason}`}>{r.name}：{r.reason}</li>)}</ul>}</div>}
    </div>}
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr>{canBulkDelete && <th className="px-4 py-3"><input type="checkbox" aria-label="選取本頁前 50 筆學員名單" checked={allSelected} onChange={() => { setPreview(false); setSelected(allSelected ? [] : selectable.map((r) => r.studentId!)); }}/></th>}<th className="px-4 py-3">人物</th><th className="px-4 py-3">狀態</th><th className="px-4 py-3">正式課程</th><th className="px-4 py-3">影片</th><th className="px-4 py-3">待開通</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y">
      {rows.map((p) => <tr key={p.key} className={p.archived ? "bg-gray-50 text-gray-400" : ""}>{canBulkDelete && <td className="px-4 py-3"><input type="checkbox" disabled={!p.studentId} aria-label={`選取 ${p.name}`} checked={Boolean(p.studentId && selected.includes(p.studentId))} onChange={() => p.studentId && toggle(p.studentId)}/></td>}<td className="px-4 py-3"><div className="font-medium text-gray-900">{p.name}</div><div className="text-xs text-gray-500">{p.email || p.phone || "無聯絡資料"}</div></td><td className="px-4 py-3"><div className="mb-1">{p.registered ? <span className="text-green-700">已註冊</span> : <span className="text-amber-700">未註冊</span>}</div><div className="flex max-w-72 flex-wrap gap-1">{p.flags.filter((f) => f !== "HAS_ACCESS").map((f) => <span key={f} className="rounded bg-gray-100 px-1.5 py-0.5 text-[11px] text-gray-600">{labels[f]}</span>)}{p.deleteStatus === "PROTECTED" && <span className="rounded bg-red-100 px-1.5 py-0.5 text-[11px] text-red-700">權限保護</span>}{p.deleteStatus === "ELIGIBLE" && <span className="rounded bg-green-100 px-1.5 py-0.5 text-[11px] text-green-700">可安全刪除</span>}</div></td><td className="px-4 py-3">{p.historyCount}</td><td className="px-4 py-3">{p.enrollmentCount}</td><td className="px-4 py-3">{p.pendingCount}</td><td className="px-4 py-3 text-right"><Link href={hrefFor(p)} className="font-medium text-blue-600 hover:underline">完整資料 →</Link></td></tr>)}
      {rows.length === 0 && <tr><td colSpan={canBulkDelete ? 7 : 6} className="px-4 py-10 text-center text-gray-400">找不到符合條件的人物</td></tr>}
    </tbody></table></div>
  </section>;
}
