"use server";
import ExcelJS from "exceljs";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db";
import { requireEditor } from "@/lib/auth/staff";
import { decodeCsvBuffer } from "@/lib/csv";
export type StudentImportState={error?:string;success?:string; imported?:number; histories?:number}|null;
const aliases={email:["email","信箱","電子信箱","e-mail"],name:["姓名","name","學員姓名"],phone:["電話","手機","phone"],course:["課程","課程名稱","course"],date:["上課日期","日期","date"],note:["備註","note"]};
const val=(row:string[],headers:string[],key:keyof typeof aliases)=>{const i=headers.findIndex(h=>aliases[key].includes(h.toLowerCase()));return i<0?"":(row[i]??"").trim()};
export async function importStudentHistory(_p:StudentImportState,fd:FormData):Promise<StudentImportState>{await requireEditor();const f=fd.get("file");if(!(f instanceof File)||!f.size)return{error:"請選擇 CSV 或 XLSX 檔"};let rows:string[][]=[];try{if(/\.csv$/i.test(f.name))rows=decodeCsvBuffer(await f.arrayBuffer()).split(/\r?\n/).filter(Boolean).map(x=>x.split(",").map(v=>v.trim().replace(/^"|"$/g,"")));else{const wb=new ExcelJS.Workbook();await wb.xlsx.load(await f.arrayBuffer());const ws=wb.worksheets[0];rows=ws.getSheetValues().slice(1).map((r:any)=>r.slice(1).map((v:any)=>String(v??"").trim()));}}catch{return{error:"檔案無法解析，請使用 CSV 或 XLSX"}}if(rows.length<2)return{error:"檔案沒有資料列"};const headers=rows.shift()!.map(x=>x.toLowerCase());if(!headers.some(h=>aliases.email.includes(h)))return{error:"需要 Email／信箱欄位"};let imported=0,histories=0;for(const row of rows){const email=val(row,headers,"email").toLowerCase();if(!email.includes("@"))continue;const record=await prisma.studentRecord.upsert({where:{email},update:{name:val(row,headers,"name")||undefined,phone:val(row,headers,"phone")||undefined},create:{email,name:val(row,headers,"name")||null,phone:val(row,headers,"phone")||null}});imported++;const course=val(row,headers,"course");if(course){const date=val(row,headers,"date");await prisma.studentCourseHistory.create({data:{studentId:record.id,courseName:course,attendedAt:date?new Date(date):null,note:val(row,headers,"note")||null,source:"IMPORT"}});histories++;}}revalidatePath("/admin/students");return{success:"匯入完成",imported,histories};}
