"use client";
import { useActionState, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { requestCourseImageUploadUrl } from "@/actions/admin";
import { createKnowledgeArticle, deleteKnowledgeArticle, updateKnowledgeArticle, type KnowledgeFormState } from "@/actions/knowledge";

type Article = { id: string; slug: string; title: string; summary: string; content: string; coverImage: string | null; images: string[]; tags: string[]; visibility: string; status: string; publishedAt: string | null; unpublishAt: string | null; createdAt: Date; updatedAt: Date };
async function upload(file: File) { const signed = await requestCourseImageUploadUrl(file.type, "article"); if (!signed.ok) return { error: signed.error }; const { error } = await createClient().storage.from(signed.bucket).uploadToSignedUrl(signed.path, signed.token, file, { contentType: file.type }); return error ? { error: error.message } : { url: signed.publicUrl }; }
function Images({ initial = [], cover = "" }: { initial?: string[]; cover?: string }) { const [coverUrl,setCoverUrl]=useState(cover); const [images,setImages]=useState(initial); const [msg,setMsg]=useState(""); const add=async(files:FileList|null, isCover=false)=>{if(!files?.[0])return;const r=await upload(files[0]); if(r.url){if(isCover)setCoverUrl(r.url);else setImages(v=>[...v,r.url]);}else setMsg(r.error??"上傳失敗")}; return <><input type="hidden" name="coverImage" value={coverUrl}/>{coverUrl && <img src={coverUrl} alt="封面" className="h-24 rounded"/>}<label className="block text-sm">文章封面 <input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{add(e.target.files,true);e.target.value=""}} /></label>{images.map(url=><input key={url} type="hidden" name="images" value={url}/>)}<div className="flex flex-wrap gap-2">{images.map(url=><span key={url} className="rounded bg-gray-100 px-2 py-1 text-xs">圖片 <button type="button" className="text-red-600" onClick={()=>setImages(v=>v.filter(x=>x!==url))}>×</button></span>)}<label className="text-sm text-indigo-600 underline">新增內文圖片<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{add(e.target.files);e.target.value=""}}/></label></div>{msg&&<p className="text-xs text-red-600">{msg}</p>}</>; }
function Fields({ article }: { article?: Article }) { return <div className="space-y-2"><div className="flex flex-wrap gap-2"><input required name="slug" defaultValue={article?.slug} placeholder="網址代稱，例如 dean-market-view" className="rounded border px-3 py-2 text-sm"/><input required name="title" defaultValue={article?.title} placeholder="文章標題" className="min-w-64 flex-1 rounded border px-3 py-2 text-sm"/></div><textarea required name="summary" defaultValue={article?.summary} rows={2} placeholder="摘要" className="w-full rounded border px-3 py-2 text-sm"/><textarea required name="content" defaultValue={article?.content} rows={10} placeholder="文章內文（可用與自訂頁相同的格式）" className="w-full rounded border px-3 py-2 text-sm"/><Images initial={article?.images} cover={article?.coverImage??""}/><div className="flex flex-wrap gap-2"><input name="tags" defaultValue={article?.tags.join("、")} placeholder="標籤，以逗號分隔" className="rounded border px-3 py-2 text-sm"/><select name="visibility" defaultValue={article?.visibility??"PUBLIC"} className="rounded border px-3 py-2 text-sm"><option value="PUBLIC">公開閱讀</option><option value="SUBSCRIBER">訂閱會員限定</option></select><select name="status" defaultValue={article?.status??"DRAFT"} className="rounded border px-3 py-2 text-sm"><option value="DRAFT">草稿</option><option value="PUBLISHED">發布</option><option value="UNPUBLISHED">下架</option></select></div></div>; }
function Feedback({state}:{state:KnowledgeFormState}) {return state?.error?<p className="text-sm text-red-600">{state.error}</p>:state?.success?<p className="text-sm text-green-700">{state.success}</p>:null}
function Create(){const [state,action,pending]=useActionState<KnowledgeFormState,FormData>(createKnowledgeArticle,null);return <form action={action} className="space-y-3 rounded-xl border border-dashed p-4"><h2 className="font-semibold">新增文章</h2><Fields/><button disabled={pending} className="rounded bg-black px-4 py-2 text-sm text-white">{pending?"建立中…":"建立文章"}</button><Feedback state={state}/></form>}
function Card({article}:{article:Article}){const [state,action,pending]=useActionState<KnowledgeFormState,FormData>(updateKnowledgeArticle.bind(null,article.id),null);return <details className="rounded-xl border"><summary className="cursor-pointer px-4 py-3"><span className="font-medium">{article.title}</span><span className="ml-2 text-xs text-gray-400">{article.status} · {article.visibility}</span></summary><form action={action} className="space-y-3 border-t p-4"><Fields article={article}/><button disabled={pending} className="rounded border px-3 py-1.5 text-sm">{pending?"儲存中…":"儲存"}</button><button type="button" className="ml-3 text-sm text-red-600" onClick={()=>{if(confirm(`確定刪除「${article.title}」？`))deleteKnowledgeArticle(article.id,article.slug)}}>刪除</button><Feedback state={state}/></form></details>}
export function KnowledgeManager({articles}:{articles:Article[]}){return <div className="space-y-6"><Create/><section className="space-y-3"><h2 className="text-lg font-bold">既有文章</h2>{articles.map(article=><Card key={article.id} article={article}/>)}{!articles.length&&<p className="text-sm text-gray-400">尚無文章。</p>}</section></div>}
