import Link from "next/link";
import { prisma } from "@/lib/db";
import { pageGuardFullAdmin } from "@/lib/auth/staff";
import { buildStudentMergePreview, groupExactDuplicateStudents, type MergeStudent } from "@/lib/duplicate-students";
import { bulkMergeStudentRecordsAction, claimStudentToMemberAction, mergeStudentRecordsAction } from "@/actions/person-roster";
import { getProfilesByEmails } from "@/lib/supabase/admin";
import { MergeStudentForm } from "../[kind]/[id]/merge-form";
import { ClaimForm } from "../[kind]/[id]/claim-form";
import { BulkMergeForm } from "./bulk-merge-form";
export const dynamic="force-dynamic";export const metadata={title:"重複學員待確認"};
const date=(v:Date|null)=>v?.toLocaleDateString("zh-TW",{timeZone:"Asia/Taipei"})||"未記錄";
function serializePreview(source:MergeStudent,target:MergeStudent){const p=buildStudentMergePreview(source,target);return{...p,moveHistories:p.moveHistories.map(h=>`${h.courseName}（${date(h.attendedAt)}）`),duplicateHistories:p.duplicateHistories.map(h=>`${h.courseName}（${date(h.attendedAt)}）`),moveEngagements:p.moveEngagements.map(e=>`${e.title}（${date(e.occurredAt)}）`),duplicateEngagements:p.duplicateEngagements.map(e=>`${e.title}（${date(e.occurredAt)}）`)}}
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;merged?:string}>}){await pageGuardFullAdmin();const params=await searchParams;const q=(params.q??"").trim().toLowerCase();
  const students=await prisma.studentRecord.findMany({where:{email:{not:null}},select:{id:true,name:true,email:true,phone:true,claimedUserId:true,legacyAccessStatus:true,createdAt:true,histories:{select:{id:true,courseName:true,attendedAt:true}},engagements:{select:{id:true,type:true,title:true,occurredAt:true}},_count:{select:{histories:true,engagements:true}}}});
  const rows=students.map(s=>({...s,historyCount:s._count.histories,engagementCount:s._count.engagements}));const groups=groupExactDuplicateStudents(rows).filter(g=>!q||`${g[0].name} ${g[0].email}`.toLowerCase().includes(q));
  const unclaimed=rows.filter(r=>!r.claimedUserId&&r.email);const profiles=await getProfilesByEmails(unclaimed.map(r=>r.email!));const cross=unclaimed.map(student=>({student,profile:profiles.get(student.email!.toLowerCase())})).filter(r=>r.profile).filter(r=>!q||`${r.student.name} ${r.student.email} ${r.profile?.display_name}`.toLowerCase().includes(q));
  const batchCandidates=groups.flatMap(group=>group.slice(1).map(source=>({source,target:group[0],preview:buildStudentMergePreview(source,group[0])})));const safeBatch=batchCandidates.filter(item=>item.preview.canMerge).map(({source,target,preview})=>({value:`${source.id}:${target.id}`,sourceLabel:`${source.name||source.email||source.id}（${date(source.createdAt)}）`,targetLabel:target.name||target.email||target.id,moveCount:preview.moveHistories.length+preview.moveEngagements.length,duplicateCount:preview.duplicateHistories.length+preview.duplicateEngagements.length}));
  return <div className="space-y-5"><header><Link href="/admin/people" className="text-sm text-blue-600">← 回學員與名單</Link><h1 className="mt-2 text-2xl font-bold">重複學員待確認</h1><p className="text-sm text-gray-500">先看差異，再逐筆人工確認；不會自動合併。</p></header>{params.merged==="1"&&<div className="rounded bg-green-50 p-3 text-green-700">合併完成，清單已重新計算。</div>}<form className="flex gap-2"><input name="q" defaultValue={q} placeholder="搜尋姓名或 Email" className="flex-1 rounded border px-3 py-2"/><button className="rounded bg-black px-4 text-white">搜尋</button></form>
    <section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold text-blue-900">跨來源身分待確認：{cross.length} 組</h2><p className="text-sm text-gray-600">會員帳號＋未認領歷史卡應做身分連結，不刪除資料。</p>{cross.map(({student,profile})=><div key={student.id} className="mt-3 rounded bg-white p-4"><div className="grid gap-2 text-sm md:grid-cols-4"><span>學員卡：{student.name||"未填姓名"}</span><span>會員：{profile!.display_name||profile!.email}</span><span>課程／活動：{student.historyCount}／{student.engagementCount}</span><Link href={`/admin/people/student/${student.id}`} className="text-blue-600">查看完整資料</Link></div><ClaimForm action={claimStudentToMemberAction.bind(null,student.id,profile!.id)} label={`${profile!.display_name||profile!.email}（${profile!.email}）`}/></div>)}</section>
    <div className="text-sm text-gray-500">同姓名＋同 Email 多卡：{groups.length} 組</div>{groups.length>0&&<BulkMergeForm key={safeBatch.map(item=>item.value).join(",")} action={bulkMergeStudentRecordsAction} candidates={safeBatch} blockedCount={batchCandidates.length-safeBatch.length}/>} {groups.map((group,index)=>{const target=group[0];return <section key={target.id} className="rounded-xl border bg-white p-5"><h2 className="font-bold">{target.name} <span className="font-normal text-gray-500">{target.email}</span></h2><p className="text-xs text-gray-400">第 {index+1} 組，共 {group.length} 張卡</p><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-2">建議</th><th className="p-2">手機</th><th className="p-2">會員</th><th className="p-2">課程／活動</th><th className="p-2">建立</th><th></th></tr></thead><tbody>{group.map((r,i)=><tr key={r.id} className="border-t"><td className="p-2">{i===0?"推薦保留":"合併來源"}</td><td className="p-2">{r.phone||"—"}</td><td className="p-2">{r.claimedUserId?"已認領":"未認領"}</td><td className="p-2">{r.historyCount}／{r.engagementCount}</td><td className="p-2">{date(r.createdAt)}</td><td><Link href={`/admin/people/student/${r.id}`} className="text-blue-600">查看</Link></td></tr>)}</tbody></table></div><div className="mt-4 rounded bg-purple-50 p-3"><b className="text-sm text-purple-900">保留：{target.name}（課程 {target.historyCount}／活動 {target.engagementCount}）</b>{group.slice(1).map(source=><MergeStudentForm key={source.id} sourceName={`${source.name}｜建立於 ${date(source.createdAt)}`} action={mergeStudentRecordsAction.bind(null,source.id,target.id)} returnTo="/admin/people/duplicates" preview={serializePreview(source,target)}/>)}</div></section>})}{!groups.length&&!cross.length&&<div className="rounded-xl border p-10 text-center text-gray-400">沒有符合的候選</div>}</div>}
