"use client";
import { useActionState, useState } from "react";
import type { SessionHistorySyncState } from "@/actions/session-history-sync";
import type { HistorySyncPreview } from "@/lib/session-history-sync";

export function SyncForm({ rows, action }: { rows: HistorySyncPreview[]; action: (prev: SessionHistorySyncState, fd: FormData) => Promise<SessionHistorySyncState> }) {
  const selectable = rows.filter((r) => r.status === "READY"); const [selected, setSelected] = useState(selectable.map((r) => r.signupId)); const [state, formAction, pending] = useActionState(action, null);
  return <form action={formAction}><div className="mb-4 rounded-lg bg-blue-50 p-3 text-sm">這裡同步的是「有效報名名單」，不等同實際簽到；只建立歷史履歷，不開通影片。可新增 {selectable.length}、已同步 {rows.filter((r) => r.status === "ALREADY").length}、需人工確認 {rows.filter((r) => ["CONFLICT","NO_CONTACT"].includes(r.status)).length}。</div><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3"></th><th className="p-3">姓名</th><th className="p-3">聯絡資料</th><th className="p-3">判定</th></tr></thead><tbody>{rows.map((r) => <tr key={r.signupId} className="border-t"><td className="p-3"><input type="checkbox" name="signupIds" value={r.signupId} disabled={r.status !== "READY"} checked={selected.includes(r.signupId)} onChange={() => setSelected((cur) => cur.includes(r.signupId) ? cur.filter((id) => id !== r.signupId) : [...cur, r.signupId])}/></td><td className="p-3">{r.name}</td><td className="p-3 text-gray-500">{r.email || r.phone || "無"}</td><td className="p-3">{{READY:"可新增",ALREADY:"已同步",NO_CONTACT:"無聯絡資料",CONFLICT:"身分衝突"}[r.status]}</td></tr>)}</tbody></table></div><button disabled={pending || !selected.length} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white disabled:opacity-40">{pending ? "同步中…" : `同步 ${selected.length} 筆上課歷史`}</button>{state?.error && <p className="mt-2 text-red-600">{state.error}</p>}{state && !state.error && <p className="mt-2 text-green-700">新增 {state.created}、略過 {state.skipped}、衝突 {state.conflicts}</p>}</form>;
}
